export const PROFILE = {
  name: 'Jasz Cawil',
  logo: '<Jasz Cawil/>',
  role: 'Front-end Web Developer',
  email: 'iamjaszemail@gmail.com',
  phone: '+63 976 358 6665',
  phoneHref: '+639763586665',
  website: 'jaszcawil.github.io',
  websiteHref: 'https://jaszcawil.github.io/',
  location: 'General Trias, Cavite, PH',
  languages: 'English, Filipino',
  social: {
    github: 'https://github.com/jaszcawil',
    linkedin: 'https://linkedin.com/in/jaszcawil',
    facebook: 'https://www.facebook.com/thisisjasz/',
    youtube: 'https://www.youtube.com/@JaszCawilYT',
  },
};

export const SKILL_DEFS = [
  ['HTML', 'tag-accent', 18],
  ['CSS', 'tag-accent', 18],
  ['JavaScript', 'tag-accent', 18],
  ['WordPress', 'tag-accent', 16],
  ['jQuery', 'tag-neutral', 14.5],
  ['API Integration', 'tag-neutral', 14.5],
  ['SEO', 'tag-neutral', 14.5],
  ['Accessibility', 'tag-neutral', 14.5],
  ['Figma', 'tag-neutral', 14.5],
  ['Photoshop', 'tag-neutral', 14.5],
  ['Git', 'tag-neutral', 14.5],
  ['SCSS', 'tag-neutral', 14.5],
  ['Elementor', 'tag-neutral', 13],
  ['WooCommerce', 'tag-neutral', 13],
  ['VS Code', 'tag-outline', 12.5],
  ['Screaming Frog', 'tag-outline', 12.5],
  ['GA4', 'tag-outline', 12.5],
  ['PageSpeed Insights', 'tag-outline', 12.5],
  ['Schema Validator', 'tag-outline', 12.5],
  ['Yoast SEO', 'tag-outline', 12.5],
  ['Problem Solving', 'tag-accent-2', 14.5],
  ['Team Leadership', 'tag-accent-2', 14.5],
];

export const JOBS = [
  {
    id: 'job1',
    role: 'Web Developer',
    company: 'Langley Compass Group',
    dates: 'August 2026 – Present',
    bullets: [
      'Development and maintenance of company websites.',
      'Development and maintenance of company web applications.',
    ],
    stack: ['WordPress', 'HTML', 'CSS', 'JavaScript', 'SEO', 'C#', '.NET', 'Blazor', 'SQL', 'Git',],
  },
  {
    id: 'job2',
    role: 'Front-end Web Developer',
    company: 'KMC MAG Solutions Inc.',
    dates: 'Jun 2023 – Feb 2026',
    bullets: [
      'Landing page creation and maintenance.',
      'Page optimization, SEO, and accessibility.',
      'Locator page development using Google Maps.',
    ],
    stack: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'API', 'SEO', 'Figma', 'Git'],
  },
  {
    id: 'job3',
    role: 'Senior UI/UX Developer',
    company: 'Cafe24 Philippines',
    dates: 'Feb 2014 – May 2023',
    bullets: [
      'Led a team of junior developers.',
      'PSD to WordPress development.',
      'In-house plugin CMS creation.',
      'E-commerce website development.',
    ],
    stack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'jQuery', 'WordPress', 'Photoshop', 'Git'],
  },
  {
    id: 'job4',
    role: 'Web Developer (Freelance)',
    company: 'Music Gear Distribution',
    dates: 'Feb 2019 – Apr 2025',
    bullets: ["Developed and maintained the company's website."],
    stack: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'WooCommerce'],
  },
  {
    id: 'job5',
    role: 'Web Developer (Freelance)',
    company: 'ATOM PH',
    dates: 'Jan 2020 – Mar 2021',
    bullets: ["Developed and maintained the organization's website."],
    stack: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'WooCommerce'],
  },
  {
    id: 'job6',
    role: 'Web Developer',
    company: 'HIDRetrofit',
    dates: 'Jan 2013 – Feb 2014',
    bullets: ["Developed and maintained the shop's website."],
    stack: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'WordPress'],
  },
];
